# Generated by Django 5.0.4 on 2024-04-20 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacoes',
            name='observacao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
